# Site settings
title: 2023工作总结             # 你的网站标题
description: 2023年高鹏工作摘要     # 一个简短的描述
url: "https://minorcaster.github.io" # 网站URL，确保替换为你的GitHub用户名

# Build settings
remote_theme: pages-themes/minima      # 使用 Slate 主题

# Slate theme settings
# 此处可以添加适用于Slate主题的特定配置选项

# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins
# 如果你需要额外的Jekyll插件，可以在这里启用
plugins:
  - jekyll-feed                       # 例如：启用自动feed插件
